# Path to reference genome fasta file
ref: '/home/quentinboone/Bureau/data/other/goat_genome.fa'
# ref: '/work/project/seqoccin/svdetection/test_pipeline/q_test/data/goat_genome.fa'

# Sample tsv file. Is composed of two columns, sample and either path or bam_path.
# path accept sequence files of PacBio reads separated by comma in the following format: subreads.bam, fastq, fq.gz, ccs.bam
# bam_accept a bam file previously produce by pbmm2
samples: 'samples.tsv'

# Datatype in the sample file. Either 'CLR', 'CCS' or 'ONT'
# Any other value will disable SNP calling
datatype: 'CLR' 

# Max length for insertion and duplication calling
# pbsv call default is 10k
max-length: 20000

# Path to the directory that will contain the output files.
# The path is relative to where your snakemake file is by default.
# if the directory doesn't exist it will be created.
workdir: '/home/quentinboone/Bureau/v11/goat_test'

# ulimit default is 1024 but can cause samtools sort to crash despite
# large memory allocations. If samtools sort crashes try giving more memory
# in cluster.yaml. If this still fails you can increase the ulimit here.
ulimit: 4096

# Annotation, if present use the faste file to annotate SV
# A new INFO filed called SVANN will contain the fasta ID if there is a match
# annotation: 'annotation.fasta'
